# Variable
EXE = reversi

# Special rules and targets
.PHONY: all build clean help

# Rules and targets
all: build

build:
	@cd src && $(MAKE)
	@cp -f src/$(EXE) ./

clean:
	@cd src && $(MAKE) clean
	@rm -f *~ *.o $(EXE)

help:
	@echo "Usage :"
	@echo "  make all   --> Build"
	@echo "  make clean --> Remove all files generated by make"
	@echo "  make help  --> Display this help"
